name: 'Cleanup Repository'
description: 'Remove caches, releases, tags e packages. Opcionalmente reescreve o histórico da branch principal.'
inputs:
  token:
    description: 'Token de acesso pessoal do GitHub (PAT) com permissões necessárias.'
    required: true
  delete_caches:
    description: 'Se deve remover os caches'
    required: false
    default: 'true'
  delete_actions:
    description: 'Se deve remover as execuções de actions'
    required: false
    default: 'true'
  delete_packages:
    description: 'Se deve remover os packages'
    required: false
    default: 'true'
  delete_releases:
    description: 'Se deve remover as releases'
    required: false
    default: 'true'
  delete_tags:
    description: 'Se deve remover as tags'
    required: false
    default: 'true'
  delete_branches:
    description: 'Se deve remover as branches obsoletas'
    required: false
    default: 'true'
  clean_history:
    description: 'Se deve reescrever o histórico da branch padrão (commit único).'
    required: false
    default: 'false'
  commit_message:
    description: 'Mensagem do commit inicial (opcional)'
    required: false
    default: 'chore: add project structure'
runs:
  using: 'composite'
  steps:
    - name: Limpar caches de Actions (GH CLI)
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        if [[ "${{ inputs.delete_caches }}" == "true" ]]; then
          echo "--- CACHES DE ACTIONS ---"
          gh cache delete --all || echo "Nenhum cache encontrado para excluir."
        fi

    - name: Executar script de limpeza (Releases, Tags, Packages, Branches, Actions)
      uses: actions/github-script@v9
      with:
        github-token: ${{ inputs.token }}
        script: |
          const flags = {
            actions: "${{ inputs.delete_actions }}",
            packages: "${{ inputs.delete_packages }}",
            releases: "${{ inputs.delete_releases }}",
            branches: "${{ inputs.delete_branches }}",
            tags: "${{ inputs.delete_tags }}"
          };
          const cleanup = require('${{ github.action_path }}/cleanup.js');
          await cleanup({github, context, core, flags});

    - name: Configurar Git para limpeza de histórico
      if: inputs.clean_history == 'true'
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Executar limpeza do histórico
      if: inputs.clean_history == 'true'
      shell: bash
      env:
        CLEANUP_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ github.repository }}
        MAIN_BRANCH: ${{ github.event.repository.default_branch }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
      run: bash ${{ github.action_path }}/clean-history.sh
